### ISSUE TITLE
Unable to connect AC even on IP

### ISSUE THREAD

**Issue by dirkronsmans** [rapi3/HA-OS-Gree#2]
```
2024-10-08 15:25:37.614 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-08 15:25:37.615 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gree which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-08 15:29:01.457 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 107, in datagram_received
    obj["pack"] = DeviceProtocol2.decrypt_payload(obj["pack"], key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 131, in decrypt_payload
    decrypted = cipher.decrypt(decoded).decode()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/Crypto/Cipher/_mode_ecb.py", line 196, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode
2024-10-08 15:30:42.549 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 107, in datagram_received
    obj["pack"] = DeviceProtocol2.decrypt_payload(obj["pack"], key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/greeclimate/network.py", line 131, in decrypt_payload
    decrypted = cipher.decrypt(decoded).decode()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/Crypto/Cipher/_mode_ecb.py", line 196, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode

```

**Comment by rapi3** [comment]
Hi,
I am using it without any problem with version:

Core 2024.3.3
Supervisor 2024.10.0
Operating System 12.3
Frontend 20240307.0

I think they changed a lot in the new version and the integration needs an update which I can't do right now.

**Comment by nevimID** [comment]
Hello,
same problem > so would you have time for an update?

**Comment by rapi3** [comment]
Hello,
Sorry, I'm not brave enough to update my running HA, still running:

Core 2024.3.3
Supervisor 2024.10.3
Operating System 12.3
Frontend 20240307.0

**Comment by rapi3** [comment]
> Hello, same problem > so would you have time for an update?

What version are you using ?

**Comment by service-paradis** [comment]
Does not work for me using:

Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6

**Comment by rapi3** [comment]
Hi,
There is one feedback that it is working with:
Core	2025.3.1
Supervisor	2025.03.2
Operating System	14.2
Frontend	20250306.0

https://github.com/rapi3/HA-OS-Gree/discussions/3#discussioncomment-12445833

At this point I update and it is ok with latest supervisor:
Core 2024.3.3
**Supervisor 2025.03.2**
Operating System 12.3
Frontend 20240307.0

**Comment by rapi3** [comment]
Next update that it is ok for me:
Core 2024.3.3
**Supervisor 2025.03.2
Operating System 14.2**
Frontend 20240307.0

**Comment by rapi3** [comment]
And finally last update that _HA Gree Custom Integration_ it is also OK:
**Core 2025.3.1
Supervisor 2025.03.2
Operating System 14.2
Frontend 20250306.0**
